package it.italiaonline.rnd

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author gsus
 * @date 10-03-2017 12.22
 */
@Slf4j
class Sha1Sum {
	/**
	 * This method returns always true.
	 */
	Boolean someSha1SumMethod() {
		true
	}
}
